// plans.config.js — Single source of truth
// CR-2: `modules` = the single source of gating (identical to the front-end src/config/plans.config.js,
// manual sync — D3). Prices removed (D2). Enterprise handled everywhere.
const MODULES_BASE = ['coach', 'nova', 'wellbeing', 'dashboard', 'copil', 'matrix']
const MODULES_GROWTH = [...MODULES_BASE, 'import', 'playbook', 'resources']
const MODULES_ELITE = [...MODULES_GROWTH, 'email', 'notif', 'okr', 'roadmap']
export const PLANS = {
  starter: { key: 'starter', modules: MODULES_BASE, currency: 'EUR', billingPeriod: 'month', maxSeats: 3, maxClients: 50, features: { dashboard: true, tasks: true, smartMatrix: true, coachAI: true, healthChat: true, emailTemplates: true, copilTemplates: true, wellbeing: true, csResources: false, csvImport: false, manualPlaybooks: false, advancedDashboardKpis: false, aiAutoPlaybooks: false, aiEmailStudio: false, okrTracker: false, productRoadmap: false, ssoSaml: false, dedicatedApi: false, prioritySupport: false, tailoredOnboarding: false, complianceAudit: false, unlimitedViewers: false } },
  growth: { key: 'growth', modules: MODULES_GROWTH, currency: 'EUR', billingPeriod: 'month', maxSeats: 7, maxClients: null, features: { dashboard: true, tasks: true, smartMatrix: true, coachAI: true, healthChat: true, emailTemplates: true, copilTemplates: true, wellbeing: true, csResources: true, csvImport: true, manualPlaybooks: true, advancedDashboardKpis: true, aiAutoPlaybooks: false, aiEmailStudio: false, okrTracker: false, productRoadmap: false, ssoSaml: false, dedicatedApi: false, prioritySupport: false, tailoredOnboarding: false, complianceAudit: false, unlimitedViewers: false } },
  elite: { key: 'elite', modules: MODULES_ELITE, currency: 'EUR', billingPeriod: 'month', maxSeats: 24, maxClients: null, features: { dashboard: true, tasks: true, smartMatrix: true, coachAI: true, healthChat: true, emailTemplates: true, copilTemplates: true, wellbeing: true, csResources: true, csvImport: true, manualPlaybooks: true, advancedDashboardKpis: true, aiAutoPlaybooks: true, aiEmailStudio: true, okrTracker: true, productRoadmap: true, ssoSaml: false, dedicatedApi: false, prioritySupport: false, tailoredOnboarding: false, complianceAudit: false, unlimitedViewers: false } },
  enterprise: { key: 'enterprise', modules: MODULES_ELITE, currency: 'EUR', billingPeriod: 'month', maxSeats: null, maxClients: null, features: { dashboard: true, tasks: true, smartMatrix: true, coachAI: true, healthChat: true, emailTemplates: true, copilTemplates: true, wellbeing: true, csResources: true, csvImport: true, manualPlaybooks: true, advancedDashboardKpis: true, aiAutoPlaybooks: true, aiEmailStudio: true, okrTracker: true, productRoadmap: true, ssoSaml: true, dedicatedApi: true, prioritySupport: true, tailoredOnboarding: true, complianceAudit: true, unlimitedViewers: true } },
}
export const ROLES = {
  owner: { key: 'owner', level: 100, consumesSeat: true, canInvite: true, canRevoke: true, canChangeRoles: true, canManageBilling: true, canViewBilling: true, canDeleteOrg: true, permissions: { clients: { read: 'all', write: 'all' }, tasks: { read: 'all', write: 'all' }, projects: { read: 'all', write: 'all' }, playbooks: { read: 'all', write: 'all' }, kpis: { read: 'all', write: 'all' }, okrs: { read: 'all', write: 'all' }, emails: { read: 'all', write: 'all' }, roadmap: { read: 'all', write: 'all' }, team: { read: 'all', write: 'all' }, settingsPersonal: { read: 'own', write: 'own' }, settingsOrg: { read: 'all', write: 'all' } } },
  admin: { key: 'admin', level: 50, consumesSeat: true, canInvite: true, canRevoke: true, canChangeRoles: false, canManageBilling: false, canViewBilling: true, canDeleteOrg: false, permissions: { clients: { read: 'all', write: 'all' }, tasks: { read: 'all', write: 'all' }, projects: { read: 'all', write: 'all' }, playbooks: { read: 'all', write: 'all' }, kpis: { read: 'all', write: 'all' }, okrs: { read: 'all', write: 'all' }, emails: { read: 'all', write: 'all' }, roadmap: { read: 'all', write: 'all' }, team: { read: 'all', write: 'all' }, settingsPersonal: { read: 'own', write: 'own' }, settingsOrg: { read: 'all', write: 'all' } } },
  member: { key: 'member', level: 10, consumesSeat: true, canInvite: false, canRevoke: false, canChangeRoles: false, canManageBilling: false, canViewBilling: false, canDeleteOrg: false, permissions: { clients: { read: 'all', write: 'own' }, tasks: { read: 'all', write: 'own' }, projects: { read: 'all', write: 'own' }, playbooks: { read: 'all', write: 'own' }, kpis: { read: 'all', write: 'own' }, okrs: { read: 'all', write: 'own' }, emails: { read: 'all', write: 'own' }, roadmap: { read: 'all', write: 'own' }, team: { read: 'all', write: 'none' }, settingsPersonal: { read: 'own', write: 'own' }, settingsOrg: { read: 'all', write: 'none' } } },
  viewer: { key: 'viewer', level: 1, consumesSeat: false, canInvite: false, canRevoke: false, canChangeRoles: false, canManageBilling: false, canViewBilling: false, canDeleteOrg: false, permissions: { clients: { read: 'all', write: 'none' }, tasks: { read: 'all', write: 'none' }, projects: { read: 'all', write: 'none' }, playbooks: { read: 'all', write: 'none' }, kpis: { read: 'all', write: 'none' }, okrs: { read: 'all', write: 'none' }, emails: { read: 'all', write: 'none' }, roadmap: { read: 'all', write: 'none' }, team: { read: 'all', write: 'none' }, settingsPersonal: { read: 'own', write: 'own' }, settingsOrg: { read: 'none', write: 'none' } } },
}
export const AUDIT_CONFIG = { enabled: true, visibleToAllMembers: true, retentionDays: null, trackedEntities: ['clients','tasks','projects','playbooks','kpis','okrs','emails','roadmap','team','invitations','settingsOrg'], trackedActions: ['create','update','delete','assign','unassign','status_change'] }
export const ORG_SETTINGS = { trialDays: 14, invitationExpiryDays: 180, maxInvitationsPerDay: 20, allowedRolesForInvite: ['owner','admin'], seatCountIncludesOwner: true }
export const INVITATION_STATUS = { pending: 'pending', accepted: 'accepted', expired: 'expired', revoked: 'revoked' }
export function getPlan(k) { return PLANS[k] || null }
export function getRole(k) { return ROLES[k] || null }
export function canPerform(r, a) { const role = ROLES[r]; return role ? !!role[a] : false }
export function hasFeature(p, f) { const plan = PLANS[p]; return plan ? !!plan.features[f] : false }
export function getMaxSeats(p) { const plan = PLANS[p]; return plan ? plan.maxSeats : 0 }
export function getMaxClients(p) { const plan = PLANS[p]; return plan ? plan.maxClients : 0 }
export function canAddSeat(p, n) { const m = getMaxSeats(p); return m === null ? true : n < m }
export function canAddViewer(p) { return hasFeature(p, 'unlimitedViewers') }
export function getSeatsUsed(members) { return members.filter(m => { const r = ROLES[m.role]; return r && r.consumesSeat }).length }
export function getAvailableRolesForInvite(p) { const r = ['admin','member']; if (hasFeature(p,'unlimitedViewers')) r.push('viewer'); return r }
export function isRoleAbove(a, b) { const ra = ROLES[a], rb = ROLES[b]; return ra && rb ? ra.level > rb.level : false }
export function canWrite(r, e, own) { const role = ROLES[r]; if (!role) return false; const p = role.permissions[e]; if (!p) return false; return p.write === 'all' || (p.write === 'own' && own) }
export function canRead(r, e, own) { const role = ROLES[r]; if (!role) return false; const p = role.permissions[e]; if (!p) return false; return p.read === 'all' || (p.read === 'own' && own) }
