// === SCALYO — Anonymization before the non-EU AI fallback (DeepSeek) ===
// A critical GDPR link. Applied ONLY when we switch over to DeepSeek
// (total Mistral outage). Goal: no identifiable personal / commercial
// data leaves the EU.
//
// Two layers:
//  1. Removal of the portfolio context block (generated by context.service.buildRichContext):
//     client account names, ARR, renewal dates, tasks. That is the main
//     source of PII injected into the prompts.
//  2. Scrubbing of universal PII (emails, amounts, dates, phone numbers) on what remains,
//     including the question freely typed by the user.
//
// Documented best-effort: the "total outage only" trigger (ai.service.js)
// minimizes the exposure frequency. Mistral (EU) stays the nominal channel.

// LYO-CONTEXT: SCALE and CITED ACCOUNT added — every block generated by
// context.service.buildRichContext MUST be listed here (the GDPR link of the fallback).
const DATA_HEADER = /^(PORTFOLIO|URGENCES|RENOUVELLEMENTS|TACHES EN RETARD|COMPTE CITE|ECHELLE|CONTEXTE UTILISATEUR|CONTEXT)/i

// Removes the structured portfolio data block (header + the "- ..." lines that follow)
function stripPortfolioBlock(text) {
  if (!text) return text
  const lines = text.split('\n')
  let inDataBlock = false
  const kept = []
  for (const line of lines) {
    const t = line.trim()
    if (DATA_HEADER.test(t)) { inDataBlock = true; continue }
    if (inDataBlock) {
      if (t === '' || t.startsWith('-') || t.startsWith('•')) continue
      inDataBlock = false
    }
    kept.push(line)
  }
  return kept.join('\n')
}

// Masks the remaining universal PII
function scrubPII(text) {
  if (!text) return text
  return text
    // emails
    .replace(/[\w.+-]+@[\w-]+\.[\w.-]+/g, '[email]')
    // montants (12 000 €, 45000 EUR, 1.2M€, 50K€…)
    .replace(/\d[\d\s.,]*\s?(k€|K€|M€|k EUR|EUR|€)/gi, '[montant]')
    // dates ISO
    .replace(/\d{4}-\d{2}-\d{2}/g, '[date]')
    // phone numbers (best-effort)
    .replace(/\+?\d[\d\s().-]{7,}\d/g, '[num]')
}

function anonymizeText(text) {
  return scrubPII(stripPortfolioBlock(text))
}

// Main entry point: receives { systemPrompt, messages }, returns an anonymized copy.
export function anonymizeForFallback({ systemPrompt, messages }) {
  return {
    systemPrompt: anonymizeText(systemPrompt || ''),
    messages: (messages || []).map(m => ({
      role: m.role,
      content: anonymizeText(m.content || ''),
    })),
  }
}
